import type { ExperiencePost, ExperienceReply } from "@/lib/types";

export const seedPosts: ExperiencePost[] = [
  {
    id: "14a6f86a-4bce-48e0-9000-000000000001",
    topic: "Starting over",
    title: "Starting over can look like falling behind",
    happened: "When I left the path everyone expected me to follow, it did not immediately feel brave. Mostly, it felt lonely. Other people continued moving forward while I was rebuilding routines I used to take for granted. I kept measuring my beginning against somebody else’s middle.",
    helped: "I started choosing one ordinary next step each week and stopped using other people’s timelines as a scoreboard.",
    wishKnown: "Starting again rarely looks impressive from the inside. Confusion and slow progress do not automatically mean you chose incorrectly.",
    authorAlias: "Anonymous Fox",
    createdAt: "2026-08-18T10:15:00.000Z",
    readingTime: "3 min read",
    contentNote: "Major life changes and academic pressure",
    tags: ["changing paths", "comparison", "new beginnings", "feeling behind"],
    status: "published",
    reactionCounts: { seen: 18, helped: 12, with_you: 9 },
    viewerReaction: null,
    replyCount: 2,
  },
  {
    id: "14a6f86a-4bce-48e0-9000-000000000002",
    topic: "Uncertainty",
    title: "I kept waiting to feel certain",
    happened: "I thought everyone else had chosen a future and received some secret confirmation that it was correct. I kept waiting for that certainty before beginning anything. It never came, and staying still slowly became its own decision.",
    helped: "Treating a choice as an experiment made it feel smaller. I picked one direction to explore instead of demanding an answer for the rest of my life.",
    wishKnown: "Clarity sometimes arrives after movement, not before it. One careful next step is enough to begin.",
    authorAlias: "Anonymous Wren",
    createdAt: "2026-08-17T14:30:00.000Z",
    readingTime: "2 min read",
    contentNote: "Uncertainty about future decisions",
    tags: ["decisions", "future", "fear", "choosing a direction"],
    status: "published",
    reactionCounts: { seen: 21, helped: 16, with_you: 11 },
    viewerReaction: null,
    replyCount: 1,
  },
  {
    id: "14a6f86a-4bce-48e0-9000-000000000003",
    topic: "Rebuilding",
    title: "Progress was quieter than I expected",
    happened: "I imagined getting my routine back would feel like a dramatic comeback. Instead, it was ordinary: finishing one task, replying to something I had avoided, and trying again after an unproductive day. Because the changes were small, I kept thinking they did not count.",
    helped: "I kept a note of small evidence instead of waiting to feel completely transformed.",
    wishKnown: "Progress does not always announce itself. Sometimes it is simply doing today what yesterday felt difficult to begin.",
    authorAlias: "Anonymous Otter",
    createdAt: "2026-08-16T09:20:00.000Z",
    readingTime: "3 min read",
    contentNote: "Burnout and rebuilding routines",
    tags: ["routines", "small steps", "confidence", "starting again"],
    status: "published",
    reactionCounts: { seen: 14, helped: 10, with_you: 8 },
    viewerReaction: null,
    replyCount: 2,
  },
  {
    id: "14a6f86a-4bce-48e0-9000-000000000004",
    topic: "School",
    title: "The result arrived before I was ready",
    happened: "I had already imagined how proud I would feel when I saw my result. When it was lower than I expected, I was disappointed and embarrassed that I had expected more. For a while, I treated that grade as a conclusion instead of information.",
    helped: "I reviewed what had worked, changed one part of how I prepared, and spoke to someone who could explain my options without judging me.",
    wishKnown: "A result can describe one performance without describing your whole future. You can be disappointed without deciding that you are a disappointment.",
    authorAlias: "Anonymous Robin",
    createdAt: "2026-08-15T12:10:00.000Z",
    readingTime: "2 min read",
    contentNote: "Disappointing academic results",
    tags: ["exams", "grades", "comparison", "academic pressure"],
    status: "published",
    reactionCounts: { seen: 29, helped: 20, with_you: 13 },
    viewerReaction: null,
    replyCount: 3,
  },
  {
    id: "14a6f86a-4bce-48e0-9000-000000000005",
    topic: "Family",
    title: "I did not need the perfect explanation",
    happened: "I used to rehearse difficult conversations, believing that if I found exactly the right words my family would immediately understand me. Sometimes they still did not, and I assumed that meant I had explained myself badly.",
    helped: "Writing down the one point I needed to communicate helped me stay clear without trying to control the whole conversation.",
    wishKnown: "You can listen, remain respectful, and still disagree. Your voice is not automatically an act of rejection.",
    authorAlias: "Anonymous Deer",
    createdAt: "2026-08-13T18:40:00.000Z",
    readingTime: "2 min read",
    contentNote: "Family expectations and disagreement",
    tags: ["expectations", "boundaries", "feeling unheard", "family"],
    status: "published",
    reactionCounts: { seen: 17, helped: 9, with_you: 12 },
    viewerReaction: null,
    replyCount: 1,
  },
  {
    id: "14a6f86a-4bce-48e0-9000-000000000006",
    topic: "Friendship",
    title: "Being included was not the same as belonging",
    happened: "I was invited and included in every conversation, but I often left feeling as though I had performed a version of myself that was easier for everyone else to like. Nothing dramatic happened. I simply became tired of feeling lonely around people.",
    helped: "Creating a little distance gave me room to notice which friendships felt mutual and calm.",
    wishKnown: "A friendship does not need to be terrible before you are allowed to admit it no longer feels right.",
    authorAlias: "Anonymous Moth",
    createdAt: "2026-08-12T16:00:00.000Z",
    readingTime: "2 min read",
    contentNote: "Loneliness and changing friendships",
    tags: ["loneliness", "belonging", "changing friendships", "self-respect"],
    status: "published",
    reactionCounts: { seen: 22, helped: 13, with_you: 15 },
    viewerReaction: null,
    replyCount: 2,
  },
  {
    id: "14a6f86a-4bce-48e0-9000-000000000007",
    topic: "Identity",
    title: "Changing my mind did not make me fake",
    happened: "I had spoken about one future for so long that changing direction felt dishonest. People associated me with that plan, and I worried they would think I had failed or never truly wanted it. The simpler truth was that I had learned more about myself.",
    helped: "I wrote down what new information had changed my thinking. That showed me the decision was thoughtful, not random.",
    wishKnown: "You are allowed to outgrow a goal after learning something new. An earlier choice can be sincere without remaining permanent.",
    authorAlias: "Anonymous Finch",
    createdAt: "2026-08-10T11:45:00.000Z",
    readingTime: "2 min read",
    contentNote: "Changing goals and personal identity",
    tags: ["changing goals", "identity", "future", "self-trust"],
    status: "published",
    reactionCounts: { seen: 16, helped: 11, with_you: 7 },
    viewerReaction: null,
    replyCount: 1,
  },
  {
    id: "14a6f86a-4bce-48e0-9000-000000000008",
    topic: "Setbacks",
    title: "The rejection did not give me directions",
    happened: "I had built so many plans around one opportunity that when it rejected me, I felt as though the rest of the year had disappeared with it. The rejection never explained what I should do next, so I had to separate the opportunity I lost from everything still possible.",
    helped: "Admitting that I cared, then choosing one small alternative action, stopped the disappointment from making every decision for me.",
    wishKnown: "A closed path can matter without becoming the final description of what remains possible.",
    authorAlias: "Anonymous Badger",
    createdAt: "2026-08-08T13:25:00.000Z",
    readingTime: "2 min read",
    contentNote: "Rejection and disappointment",
    tags: ["rejection", "applications", "setbacks", "alternative plans"],
    status: "published",
    reactionCounts: { seen: 19, helped: 14, with_you: 9 },
    viewerReaction: null,
    replyCount: 1,
  },
];

export const seedReplies: ExperienceReply[] = [
  {
    id: "24a6f86a-4bce-48e0-9000-000000000001",
    postId: seedPosts[0].id,
    authorAlias: "Anonymous Heron",
    body: "I needed the reminder that a restart has its own timeline. Thank you for leaving this here.",
    createdAt: "2026-08-20T09:10:00.000Z",
    status: "published",
  },
  {
    id: "24a6f86a-4bce-48e0-9000-000000000002",
    postId: seedPosts[0].id,
    authorAlias: "Anonymous Hare",
    body: "The difference between a beginning and somebody else’s middle is exactly what I was missing.",
    createdAt: "2026-08-21T12:05:00.000Z",
    status: "published",
  },
  {
    id: "24a6f86a-4bce-48e0-9000-000000000003",
    postId: seedPosts[1].id,
    authorAlias: "Anonymous Seal",
    body: "Calling the next choice an experiment makes it feel possible rather than permanent.",
    createdAt: "2026-08-22T15:45:00.000Z",
    status: "published",
  },
  {
    id: "24a6f86a-4bce-48e0-9000-000000000004",
    postId: seedPosts[3].id,
    authorAlias: "Anonymous Lynx",
    body: "A grade as information instead of identity is a much kinder and more useful way to see it.",
    createdAt: "2026-08-19T08:30:00.000Z",
    status: "published",
  },
];
